name: SkyblockRecreation
version: ${project.version}
main: me.chocobo.skyblockrecreation.SkyblockRecreation

commands:
  giveitem:
    description: Gives you the requested Item
    aliases: [givei, gitem]
  spawnenemy:
    description: Spawns the enemy you requested
    aliases: spawn
  setstrength:
    description: Sets your Strength
  getiteminhand:
    description: Prints the stats of the item in your hand in the chat